


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."Status" AS ENUM (
    'Pendente',
    'Em análise',
    'Reprovado',
    'Aprovado'
);


ALTER TYPE "public"."Status" OWNER TO "postgres";


CREATE TYPE "public"."Tipo" AS ENUM (
    'CNH',
    'Selfie'
);


ALTER TYPE "public"."Tipo" OWNER TO "postgres";


COMMENT ON TYPE "public"."Tipo" IS 'Tipo de documento';



CREATE OR REPLACE FUNCTION "public"."create_or_get_chat_room"("p_viagem_id" bigint) RETURNS "uuid"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
declare
  v_room_id uuid;
  v_motorista uuid := auth.uid();
  v_empresa uuid := '869ee8f6-cce2-4b9f-b54a-539ceff092a7'::uuid;
begin
  -- se já existe sala para (viagem + motorista), retorna
  select id into v_room_id
  from public.chat_rooms
  where viagem_id = p_viagem_id
    and motorista_user_id = v_motorista;

  if v_room_id is not null then
    return v_room_id;
  end if;

  -- se não existe, cria e retorna
  insert into public.chat_rooms (viagem_id, motorista_user_id, empresa_user_id)
  values (p_viagem_id, v_motorista, v_empresa)
  returning id into v_room_id;

  return v_room_id;
end;
$$;


ALTER FUNCTION "public"."create_or_get_chat_room"("p_viagem_id" bigint) OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Documentos_Motorista" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "motorista_id" "uuid",
    "url" "text" NOT NULL,
    "enviado_em" timestamp with time zone DEFAULT "now"(),
    "tipo" "public"."Tipo"
);


ALTER TABLE "public"."Documentos_Motorista" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Endereço" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "Usuario_CaminhoneiroID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "CEP" bigint NOT NULL,
    "Rua" character varying NOT NULL,
    "Bairro" "text" NOT NULL,
    "Cidade" "text" NOT NULL,
    "UF" "text" NOT NULL,
    "Numero" integer,
    "Complemento" character varying
);


ALTER TABLE "public"."Endereço" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Usuario_Caminhoneiro" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "nome" "text" NOT NULL,
    "sobrenome" "text" NOT NULL,
    "email" character varying NOT NULL,
    "cpf_cnpj" "text" NOT NULL,
    "data_nascimento" "date" NOT NULL,
    "telefone" "text" NOT NULL,
    "genero" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "foto_url" "text",
    "status" "public"."Status" DEFAULT 'Pendente'::"public"."Status"
);


ALTER TABLE "public"."Usuario_Caminhoneiro" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Veiculo" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "Usuario_CaminhoneiroID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "TamanhoVeiculo" character varying NOT NULL,
    "TipoVeiculo" "text" NOT NULL,
    "BauVeiculo" character varying NOT NULL,
    "TipoBau" character varying NOT NULL,
    "PlacaVeiculo" character varying NOT NULL,
    "RNTRC_ANTT" numeric NOT NULL
);


ALTER TABLE "public"."Veiculo" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Viagens" (
    "id" bigint NOT NULL,
    "empresa" "text",
    "produto" "text",
    "origem_cidade" "text",
    "origem_uf" "text",
    "destino_cidade" "text",
    "destino_uf" "text",
    "peso" numeric,
    "valor" numeric,
    "dimensoes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "data_limite_entrega" timestamp with time zone
);


ALTER TABLE "public"."Viagens" OWNER TO "postgres";


ALTER TABLE "public"."Viagens" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Viagens_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."chat_messages" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "room_id" "uuid" NOT NULL,
    "sender_user_id" "uuid" NOT NULL,
    "message" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."chat_messages" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."chat_rooms" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "viagem_id" bigint NOT NULL,
    "motorista_user_id" "uuid" NOT NULL,
    "empresa_user_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."chat_rooms" OWNER TO "postgres";


ALTER TABLE ONLY "public"."Endereço"
    ADD CONSTRAINT "Endereço_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Usuario_Caminhoneiro"
    ADD CONSTRAINT "Usuario_Caminhoneiro_CPF/CNPJ_key" UNIQUE ("cpf_cnpj");



ALTER TABLE ONLY "public"."Usuario_Caminhoneiro"
    ADD CONSTRAINT "Usuario_Caminhoneiro_Email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."Usuario_Caminhoneiro"
    ADD CONSTRAINT "Usuario_Caminhoneiro_Telefone_key" UNIQUE ("telefone");



ALTER TABLE ONLY "public"."Usuario_Caminhoneiro"
    ADD CONSTRAINT "Usuario_Caminhoneiro_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Veiculo"
    ADD CONSTRAINT "Veiculo_PlacaVeiculo_key" UNIQUE ("PlacaVeiculo");



ALTER TABLE ONLY "public"."Veiculo"
    ADD CONSTRAINT "Veiculo_RNTRC(ANTT)_key" UNIQUE ("RNTRC_ANTT");



ALTER TABLE ONLY "public"."Veiculo"
    ADD CONSTRAINT "Veiculo_Usuario_CaminhoneiroID_key" UNIQUE ("Usuario_CaminhoneiroID");



ALTER TABLE ONLY "public"."Veiculo"
    ADD CONSTRAINT "Veiculo_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Viagens"
    ADD CONSTRAINT "Viagens_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."chat_messages"
    ADD CONSTRAINT "chat_messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."chat_rooms"
    ADD CONSTRAINT "chat_rooms_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."chat_rooms"
    ADD CONSTRAINT "chat_rooms_viagem_id_motorista_user_id_key" UNIQUE ("viagem_id", "motorista_user_id");



ALTER TABLE ONLY "public"."Documentos_Motorista"
    ADD CONSTRAINT "documentosmotorista_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_chat_messages_room_created" ON "public"."chat_messages" USING "btree" ("room_id", "created_at");



ALTER TABLE ONLY "public"."chat_messages"
    ADD CONSTRAINT "chat_messages_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "public"."chat_rooms"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."chat_rooms"
    ADD CONSTRAINT "chat_rooms_viagem_fk" FOREIGN KEY ("viagem_id") REFERENCES "public"."Viagens"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Documentos_Motorista"
    ADD CONSTRAINT "documentosmotorista_motorista_id_fkey" FOREIGN KEY ("motorista_id") REFERENCES "public"."Usuario_Caminhoneiro"("id") ON DELETE CASCADE;



ALTER TABLE "public"."Documentos_Motorista" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Endereço" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Motorista pode ver seus veiculos" ON "public"."Veiculo" FOR SELECT USING (("auth"."uid"() = "Usuario_CaminhoneiroID"));



CREATE POLICY "Permitir INSERT do proprio motorista" ON "public"."Veiculo" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "Usuario_CaminhoneiroID"));



ALTER TABLE "public"."Usuario_Caminhoneiro" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Usuário pode inserir seus documentos" ON "public"."Documentos_Motorista" FOR INSERT TO "authenticated" WITH CHECK (("motorista_id" = "auth"."uid"()));



ALTER TABLE "public"."Veiculo" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Viagens" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "allow_select_viagens" ON "public"."Viagens" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "anon_insert" ON "public"."Usuario_Caminhoneiro" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "anon_select" ON "public"."Usuario_Caminhoneiro" FOR SELECT TO "anon" USING (true);



ALTER TABLE "public"."chat_messages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."chat_rooms" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "insert_address" ON "public"."Endereço" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "Usuario_CaminhoneiroID"));



CREATE POLICY "insert_user_authenticated" ON "public"."Usuario_Caminhoneiro" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "messages_insert_participants" ON "public"."chat_messages" FOR INSERT WITH CHECK ((("sender_user_id" = "auth"."uid"()) AND (EXISTS ( SELECT 1
   FROM "public"."chat_rooms" "r"
  WHERE (("r"."id" = "chat_messages"."room_id") AND (("auth"."uid"() = "r"."motorista_user_id") OR ("auth"."uid"() = "r"."empresa_user_id")))))));



CREATE POLICY "messages_select_participants" ON "public"."chat_messages" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."chat_rooms" "r"
  WHERE (("r"."id" = "chat_messages"."room_id") AND (("auth"."uid"() = "r"."motorista_user_id") OR ("auth"."uid"() = "r"."empresa_user_id"))))));



CREATE POLICY "motorista insere seus documentos" ON "public"."Documentos_Motorista" FOR INSERT TO "authenticated" WITH CHECK (("motorista_id" = "auth"."uid"()));



CREATE POLICY "motorista vê seus documentos" ON "public"."Documentos_Motorista" FOR SELECT TO "authenticated" USING (("motorista_id" = "auth"."uid"()));



CREATE POLICY "rooms_select_participants" ON "public"."chat_rooms" FOR SELECT USING ((("auth"."uid"() = "motorista_user_id") OR ("auth"."uid"() = "empresa_user_id")));



CREATE POLICY "select_address" ON "public"."Endereço" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "Usuario_CaminhoneiroID"));



CREATE POLICY "select_user_authenticated" ON "public"."Usuario_Caminhoneiro" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "id"));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."create_or_get_chat_room"("p_viagem_id" bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."create_or_get_chat_room"("p_viagem_id" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."create_or_get_chat_room"("p_viagem_id" bigint) TO "service_role";


















GRANT ALL ON TABLE "public"."Documentos_Motorista" TO "anon";
GRANT ALL ON TABLE "public"."Documentos_Motorista" TO "authenticated";
GRANT ALL ON TABLE "public"."Documentos_Motorista" TO "service_role";



GRANT ALL ON TABLE "public"."Endereço" TO "anon";
GRANT ALL ON TABLE "public"."Endereço" TO "authenticated";
GRANT ALL ON TABLE "public"."Endereço" TO "service_role";



GRANT ALL ON TABLE "public"."Usuario_Caminhoneiro" TO "anon";
GRANT ALL ON TABLE "public"."Usuario_Caminhoneiro" TO "authenticated";
GRANT ALL ON TABLE "public"."Usuario_Caminhoneiro" TO "service_role";



GRANT ALL ON TABLE "public"."Veiculo" TO "anon";
GRANT ALL ON TABLE "public"."Veiculo" TO "authenticated";
GRANT ALL ON TABLE "public"."Veiculo" TO "service_role";



GRANT ALL ON TABLE "public"."Viagens" TO "anon";
GRANT ALL ON TABLE "public"."Viagens" TO "authenticated";
GRANT ALL ON TABLE "public"."Viagens" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Viagens_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Viagens_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Viagens_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."chat_messages" TO "anon";
GRANT ALL ON TABLE "public"."chat_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."chat_messages" TO "service_role";



GRANT ALL ON TABLE "public"."chat_rooms" TO "anon";
GRANT ALL ON TABLE "public"."chat_rooms" TO "authenticated";
GRANT ALL ON TABLE "public"."chat_rooms" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































